# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"


NodeCount = 2

  # Centos Worker Nodes
  (1..NodeCount).each do |i|
    config.vm.define "centos#{i}" do |workernode|
      workernode.vm.box = "centos/7"
      workernode.vm.hostname = "centos#{i}.home"
      workernode.vm.network "private_network", ip: "172.42.42.10#{i}"
      workernode.vm.provider "virtualbox" do |v|
        v.name = "centos#{i}"
        v.memory = 1024
        v.cpus = 1
      end
    end
  end
end
